batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true
seed = 0
head_selection = true

[data]
cache = true
path = "data/ecom-offers"
num_policy = "noisy-quantile"

[optimizer]
lr = 0.00024262819114537424
weight_decay = 0.0001501852317298042

[model]
arch_type = "tabm"
k = 32
share_training_batches = false

[model.backbone]
n_blocks = 1
d_block = 960
dropout = 0.0

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16

[bins]
n_bins = 47

[cf_fisd]
lambda = 0.1
variant = "raw"
dataset_name = "ecom-offers"
teacher_dir = "../../cf_fisd_recovered/paper/exp/cf_fisd/_teachers/tabred/ecom-offers"
teacher_names = [
    "xgb",
    "lgbm",
    "cat",
]
