dataset = "cooking-time"
variant = "cf_fisd_only"
seed = 1
batch_size = 2048
patience = 6
n_epochs = 20
gradient_clipping_norm = 1.0
amp = true

[data]
path = "data/cooking-time"
num_policy = "standard"
cache = false

[optimizer]
type = "AdamW"
lr = 0.0003
weight_decay = 1e-05

[model]
arch_type = "tabm"
k = 16
n_blocks = 2
d_block = 384
dropout = 0.1
d_embedding = 16
n_bins = 48
cf_fisd_enabled = true
